import type { Metadata } from "next";
import { Manrope, Merriweather_Sans, Inter } from "next/font/google";
import { CartProvider } from "@/components/cart/cart-provider";
import "./globals.css";

const primary = Manrope({
  variable: "--font-primary",
  subsets: ["latin"],
});

const secondary = Inter({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ['400']
});

const tertiary = Merriweather_Sans({
  variable: "--font-tertiary",
  subsets: ["latin"],
  weight: ['400']
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${primary.variable} bg-linear-to-tr from-purple-500/90 to-purple-900/90 antialiased min-h-screen flex flex-col items-center justify-between ${secondary.variable} ${tertiary.variable} overflow-x-hidden`}>
          <CartProvider>
              {children}
          </CartProvider>
      </body>
    </html>
  );
}
